# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('section', models.IntegerField()),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('Fall', 'F'), ('Spring', 'S')], default='FALL', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('eagleid', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeerAssessment',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.TextField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessments.Course')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessments.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('eagleid', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
