# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0002_auto_20200422_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
