# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0003_auto_20200508_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='iid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peerAssessments.Instructor'),
            preserve_default=False,
        ),
    ]
