# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0004_course_iid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='iid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peerassessment',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
