# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0006_instructor_mycourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('qType', models.CharField(choices=[('Multiple Choice', 'MC'), ('TEXT', 'T')], default='Multiple Choice', max_length=20)),
                ('questionText', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='name',
            field=models.CharField(default='Delivery 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='number',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='peerassessment',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessments.PeerAssessment'),
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='questions',
            field=models.ManyToManyField(to='peerAssessments.Question'),
        ),
    ]
