# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0010_auto_20200510_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerassessment',
            name='number',
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question10Text',
            field=models.CharField(default='Question Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question10Type',
            field=models.CharField(choices=[('Multiple Choice', 'MC'), ('TEXT', 'T')], default='Multiple Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question6Text',
            field=models.CharField(default='Question Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question6Type',
            field=models.CharField(choices=[('Multiple Choice', 'MC'), ('TEXT', 'T')], default='Multiple Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question7Text',
            field=models.CharField(default='Question Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question7Type',
            field=models.CharField(choices=[('Multiple Choice', 'MC'), ('TEXT', 'T')], default='Multiple Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question8Text',
            field=models.CharField(default='Question Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question8Type',
            field=models.CharField(choices=[('Multiple Choice', 'MC'), ('TEXT', 'T')], default='Multiple Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question9Text',
            field=models.CharField(default='Question Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerassessment',
            name='question9Type',
            field=models.CharField(choices=[('Multiple Choice', 'MC'), ('TEXT', 'T')], default='Multiple Choice', max_length=20),
        ),
    ]
