# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0011_auto_20200510_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='peerassessment',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
