# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0013_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='livePAs',
            field=models.ManyToManyField(to='peerAssessments.PeerAssessment'),
        ),
    ]
