# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0014_team_livepas'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completedAssessments',
            field=models.ManyToManyField(to='peerAssessments.PeerAssessment'),
        ),
    ]
