# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0017_auto_20200511_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teams',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='peerAssessments.Course'),
        ),
    ]
