# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0018_auto_20200511_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedassessments',
            name='evalStudent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_student_name', to='peerAssessments.Student'),
            preserve_default=False,
        ),
    ]
