# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessments', '0019_completedassessments_evalstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='completedPAs',
            field=models.ManyToManyField(related_name='completedPAs', to='peerAssessments.PeerAssessment'),
        ),
    ]
